import React from 'react';
import { Layers, AlertOctagon, TrendingDown, CheckCircle2 } from 'lucide-react';

export default function FunnelView({ data }) {
  const funnel = data.funnel || {};
  const macroStages = funnel.macro_stages || [];
  const lessons = data.lesson_funnel || [];
  const totalIncomplete = funnel.total_incomplete_enrollments || 79719;
  const l1Drops = funnel.lesson_1_drop_off_count || 36017;
  const l1Share = funnel.lesson_1_drop_off_share_pct || 45.18;

  const maxLessonDrops = Math.max(...lessons.map(l => l.drop_offs || 0), 1);

  return (
    <div>
      {/* Analysis Chart from Python Pipeline */}
      <div className="card" style={{ marginBottom: '24px' }}>
        <div className="card-header">
          <div>
            <h3 className="card-title">Macro & Micro Funnel Analysis</h3>
            <p className="card-subtitle">Generated by DuckDB SQL + Python analysis pipeline</p>
          </div>
        </div>
        <img
          src="/01_macro_and_micro_funnel.png"
          alt="Macro and Micro Funnel Chart"
          style={{ width: '100%', borderRadius: '8px', marginTop: '12px', display: 'block' }}
        />
      </div>

      {/* Overview Cards */}
      <div className="grid-3">
        <div className="card">
          <div className="kpi-label">Total Incomplete Enrollments</div>
          <div className="kpi-val" style={{ color: 'var(--text-main)' }}>{totalIncomplete.toLocaleString()}</div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Out of 149,316 total enrollments (53.4%)</div>
        </div>
        <div className="card">
          <div className="kpi-label">Lesson 1 Drop-Offs</div>
          <div className="kpi-val" style={{ color: 'var(--accent-rose)' }}>{l1Drops.toLocaleString()}</div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Learners abandoned before completing Lesson 1</div>
        </div>
        <div className="card">
          <div className="kpi-label">Lesson 1 Drop Share</div>
          <div className="kpi-val" style={{ color: 'var(--accent-amber)' }}>{l1Share}%</div>
          <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>Share of all platform non-completers</div>
        </div>
      </div>

      {/* Main Grid: Macro Funnel Table & Per-Lesson Micro Funnel */}
      <div className="grid-2">
        {/* Macro Stages Breakdown */}
        <div className="card">
          <div className="card-header">
            <div>
              <h3 className="card-title">
                <Layers size={18} color="var(--accent-blue)" />
                Macro Enrollment Funnel Stages
              </h3>
              <p className="card-subtitle">Aggregated from mart_funnel (N = 149,316)</p>
            </div>
          </div>

          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Funnel Stage</th>
                  <th>Enrollments</th>
                  <th>% of Enrolled</th>
                  <th>Step Conversion</th>
                </tr>
              </thead>
              <tbody>
                {macroStages.map((stg, idx) => (
                  <tr key={stg.Stage}>
                    <td style={{ fontWeight: 600 }}>{stg.Stage}</td>
                    <td style={{ fontFamily: 'var(--font-mono)' }}>{stg.Count.toLocaleString()}</td>
                    <td>
                      <span className="badge-live" style={{ background: 'rgba(56, 189, 248, 0.1)', color: 'var(--accent-blue)', borderColor: 'rgba(56, 189, 248, 0.25)' }}>
                        {stg.Pct_of_Enrolled.toFixed(1)}%
                      </span>
                    </td>
                    <td style={{ fontFamily: 'var(--font-mono)', color: idx === 0 ? 'var(--text-muted)' : 'var(--accent-emerald)' }}>
                      {idx === 0 ? '100.0%' : `${stg.Step_Conversion_Pct.toFixed(1)}%`}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="callout-box" style={{ marginTop: '20px' }}>
            <strong>Funnel Analysis Finding:</strong> Once a learner completes Lesson 1, the step conversion to course completion jumps to <strong>61.4%</strong>. The bottleneck is strictly getting users past the initial onboarding milestone.
          </div>
        </div>

        {/* Micro Drop-offs Per Lesson */}
        <div className="card">
          <div className="card-header">
            <div>
              <h3 className="card-title">
                <TrendingDown size={18} color="var(--accent-rose)" />
                Micro Drop-Offs by Lesson Number
              </h3>
              <p className="card-subtitle">Dense-grid evaluation from mart_lesson_quiz_funnel (1.27M rows)</p>
            </div>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '10px', marginTop: '10px' }}>
            {lessons.map((les) => {
              const drops = les.drop_offs || 0;
              const barWidth = (drops / maxLessonDrops) * 100;
              const isL1 = les.lesson_number === 1;

              return (
                <div key={les.lesson_number} style={{ display: 'flex', alignItems: 'center', gap: '12px', fontSize: '0.82rem' }}>
                  <div style={{ width: '75px', fontWeight: 600, color: isL1 ? 'var(--accent-rose)' : 'var(--text-muted)' }}>
                    Lesson {les.lesson_number}
                  </div>
                  <div style={{ flex: 1, background: 'rgba(255,255,255,0.04)', height: '22px', borderRadius: '4px', position: 'relative', overflow: 'hidden' }}>
                    <div 
                      style={{ 
                        height: '100%', 
                        width: `${barWidth}%`, 
                        background: isL1 ? 'linear-gradient(90deg, #e11d48, #fb7185)' : 'linear-gradient(90deg, #3b82f6, #60a5fa)',
                        borderRadius: '3px',
                        transition: 'width 0.5s ease'
                      }}
                    />
                  </div>
                  <div style={{ width: '90px', textAlign: 'right', fontFamily: 'var(--font-mono)', fontWeight: 600, color: isL1 ? 'var(--accent-rose)' : 'var(--text-main)' }}>
                    {drops.toLocaleString()}
                  </div>
                  <div style={{ width: '65px', textAlign: 'right', color: 'var(--text-dim)', fontSize: '0.75rem' }}>
                    ({les.completion_pct}%)
                  </div>
                </div>
              );
            })}
          </div>

          <div className="callout-box callout-danger" style={{ marginTop: '20px' }}>
            <strong>Lesson 1 Drop Concentration:</strong> Exactly 36,017 learners drop out at Lesson 1. Dropouts drop sharply by 74% at Lesson 2 (9,360) and stabilize under 3,000 for later lessons.
          </div>
        </div>
      </div>
    </div>
  );
}
